version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/src/AdminUI"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
