---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: src/secrets/privkey.pem
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      # - id: pretty-format-json
      #   args:
      #     - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.23.2
  #   hooks:
  #     - id: markdownlint
  #       args:
  #         - --config=.mdl_config.json
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.23.0
  #   hooks:
  #     - id: yamllint
  # - repo: https://github.com/detailyang/pre-commit-shell
  #   rev: 1.0.5
  #   hooks:
  #     - id: shell-lint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.0
    hooks:
      - id: pyupgrade
  # Run bandit on "tests" tree with a configuration
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        name: bandit (tests tree)
        files: tests
        args:
          - --config=.bandit.yml
  # Run bandit everything but tests directory
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.1
    hooks:
      - id: bandit
        name: bandit (everything else)
        exclude: tests
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.7
    hooks:
      - id: isort
  # - repo: https://github.com/IamTheFij/docker-pre-commit
  #   rev: v2.0.0
  #   hooks:
  #     - id: docker-compose-check
  # - repo: https://github.com/prettier/prettier
  #   rev: 2.0.5
  #   hooks:
  #     - id: prettier
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
