---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: src/secrets/privkey.pem
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      # - id: pretty-format-json
      #   args:
      #     - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.23.2
  #   hooks:
  #     - id: markdownlint
  #       args:
  #         - --config=.mdl_config.json
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.23.0
  #   hooks:
  #     - id: yamllint
  # - repo: https://github.com/detailyang/pre-commit-shell
  #   rev: 1.0.5
  #   hooks:
  #     - id: shell-lint
  # - repo: https://github.com/IamTheFij/docker-pre-commit
  #   rev: v2.0.0
  #   hooks:
  #     - id: docker-compose-check
  # - repo: https://github.com/prettier/prettier
  #   rev: 2.0.5
  #   hooks:
  #     - id: prettier
