version: "3.5"
services:
  web:
    build:
      context: .
    container_name: pca-web-prod
    image: pca-web-prod:1.0
    restart: unless-stopped
    ports:
      - "4200:443"
    networks:
      - frontend
    env_file:
      - .env

networks:
  frontend:
    name: pca_frontend
