---
version: "3.5"
services:
  web:
    build:
      args:
        VERSION: "1.0.0"
      context: .
    container_name: pca-web
    image: cisagov/pca-web
    restart: unless-stopped
    ports:
<<<<<<< HEAD
      - "4200:80"
    networks:
      - frontend
      - backend
    env_file:
      - .env
=======
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: quote_txt
        target: quote.txt
>>>>>>> b1949f9b301eef109150dfcb1febfa376e3997d8

networks:
  frontend:
    name: pca_frontend
  backend:
    name: pca_backend
