---
version: "3.5"
services:
  web:
    build:
      context: .
    container_name: pca-web
    image: cisagov/pca-web
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - frontend
      - backend
    env_file:
      - .env

networks:
  frontend:
    name: pca_frontend
  backend:
    name: pca_backend
