---
version: "3.5"
services:
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: pca-web
    image: cisagov/pca-web-local
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./src/AdminUI:/app
    networks:
      - frontend
      - backend
    env_file:
      - .env
networks:
  frontend:
    name: pca_frontend
  backend:
    name: pca_backend
